import { SizeScale } from "../scale";

export const SizeSemanticGgoody = {
  "size-semantic-border-radius-none": SizeScale["size-scale-0"],
  "size-semantic-border-radius-xs": SizeScale["size-scale-10"],
  "size-semantic-border-radius-s": SizeScale["size-scale-14"],
  "size-semantic-border-radius-m": SizeScale["size-scale-16"],
  "size-semantic-border-radius-l": SizeScale["size-scale-20"],
  "size-semantic-border-radius-xl": SizeScale["size-scale-24"],
  "size-semantic-border-radius-full": SizeScale["size-scale-9999"],
  "size-semantic-icon-xxs": SizeScale["size-scale-12"],
  "size-semantic-icon-xs": SizeScale["size-scale-16"],
  "size-semantic-icon-s": SizeScale["size-scale-20"],
  "size-semantic-icon-m": SizeScale["size-scale-24"],
  "size-semantic-icon-l": SizeScale["size-scale-32"],
  "size-semantic-icon-xl": SizeScale["size-scale-40"],
  "size-semantic-icon-xxl": SizeScale["size-scale-48"],
  "size-semantic-spacing-none": SizeScale["size-scale-0"],
  "size-semantic-spacing-2": SizeScale["size-scale-2"],
  "size-semantic-spacing-4": SizeScale["size-scale-4"],
  "size-semantic-spacing-6": SizeScale["size-scale-6"],
  "size-semantic-spacing-8": SizeScale["size-scale-8"],
  "size-semantic-spacing-10": SizeScale["size-scale-10"],
  "size-semantic-spacing-12": SizeScale["size-scale-12"],
  "size-semantic-spacing-14": SizeScale["size-scale-14"],
  "size-semantic-spacing-16": SizeScale["size-scale-16"],
  "size-semantic-spacing-18": SizeScale["size-scale-18"],
  "size-semantic-spacing-20": SizeScale["size-scale-20"],
  "size-semantic-spacing-24": SizeScale["size-scale-24"],
  "size-semantic-spacing-32": SizeScale["size-scale-32"],
  "size-semantic-spacing-36": SizeScale["size-scale-36"],
  "size-semantic-spacing-40": SizeScale["size-scale-40"],
  "size-semantic-spacing-44": SizeScale["size-scale-44"],
  "size-semantic-spacing-48": SizeScale["size-scale-48"],
  "size-semantic-spacing-56": SizeScale["size-scale-56"],
  "size-semantic-spacing-64": SizeScale["size-scale-64"],
  "size-semantic-spacing-72": SizeScale["size-scale-72"],
  "size-semantic-spacing-80": SizeScale["size-scale-80"],
  "size-semantic-spacing-96": SizeScale["size-scale-96"],
  "size-semantic-spacing-120": SizeScale["size-scale-120"],
  "size-semantic-spacing-160": SizeScale["size-scale-160"],
} as const;
