name: Deploy Storybook

on:
  push:
    branches: ["main"] # main 브랜치에 push될 때 실행
    paths:
      - "packages/ui/**" # packages/ui 디렉토리의 변경사항만 감지

  # 수동으로 실행할 수 있도록 설정
  workflow_dispatch:

# netlify 배포
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: cd packages/ui && yarn build-storybook

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: "packages/ui/storybook-static"
          deploy_alias: "production"
